ALTER TABLE "ai_approval" ADD CONSTRAINT "ai_approval_org_run_fk" FOREIGN KEY ("organization_id","run_id") REFERENCES "public"."ai_run"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_approval" ADD CONSTRAINT "ai_approval_org_conversation_fk" FOREIGN KEY ("organization_id","conversation_id") REFERENCES "public"."ai_conversation"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_feature_assignment" ADD CONSTRAINT "ai_feature_assignment_org_provider_config_fk" FOREIGN KEY ("organization_id","provider_config_id") REFERENCES "public"."ai_provider_config"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ai_run" ADD CONSTRAINT "ai_run_org_conversation_fk" FOREIGN KEY ("organization_id","conversation_id") REFERENCES "public"."ai_conversation"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "backup_run" ADD CONSTRAINT "backup_run_organization_schedule_fk" FOREIGN KEY ("organization_id","schedule_id") REFERENCES "public"."backup_schedule"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "backup_run" ADD CONSTRAINT "backup_run_organization_destination_fk" FOREIGN KEY ("organization_id","destination_id") REFERENCES "public"."s3_destination"("organization_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "backup_schedule" ADD CONSTRAINT "backup_schedule_organization_destination_fk" FOREIGN KEY ("organization_id","destination_id") REFERENCES "public"."s3_destination"("organization_id","id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "docker_registry" ADD CONSTRAINT "docker_registry_organization_server_fk" FOREIGN KEY ("organization_id","server_id") REFERENCES "public"."server"("organization_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_delivery" ADD CONSTRAINT "notification_delivery_org_channel_fk" FOREIGN KEY ("organization_id","channel_id") REFERENCES "public"."notification_channel"("organization_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "s3_destination" ADD CONSTRAINT "s3_destination_organization_certificate_fk" FOREIGN KEY ("organization_id","certificate_id") REFERENCES "public"."certificate"("organization_id","id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "server" ADD CONSTRAINT "server_organization_ssh_key_fk" FOREIGN KEY ("organization_id","ssh_key_id") REFERENCES "public"."ssh_key"("organization_id","id") ON DELETE no action ON UPDATE no action;